version: "3.5"

services:
  app:
    image: ${IMAGE}:${TAG:-local}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env      
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - 0.0.0.0:8010:8000
    volumes:
      - ../src/public:/var/www/html/public
    restart: always