name: deploy app-milestone-backend to k8s (onprem)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build images
        working-directory: ./microservices/app-milestone-backend
        run: |
          make build-remote
          make push-remote

  configure:
    needs: build
    runs-on: self-hosted
    environment: production

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
      MYSQL_DB_USER: ${{ secrets.MYSQL_DB_USER }}
      MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
      MYSQL_DB_NAME: ${{ secrets.MYSQL_DB_NAME }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
      NEW_RELIC_LOG_LEVEL: ${{ secrets.NEW_RELIC_LOG_LEVEL }}
    
    steps:
      - name: Create namespace
        run: |
          NAMESPACE="lidm-app-milestone"; microk8s kubectl get namespace $NAMESPACE &> /dev/null || microk8s kubectl create namespace $NAMESPACE

      - name: Set ConfigMaps
        run: | 
          echo "
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: lidm-app-milestone-backend
          data:
            OPENAI_API_KEY: '$OPENAI_API_KEY'
            FLASK_DEBUG: '$FLASK_DEBUG'
            LOG_LEVEL: '$LOG_LEVEL'
            MYSQL_DB_HOST: '$MYSQL_DB_HOST'
            MYSQL_DB_USER: '$MYSQL_DB_USER'
            MYSQL_DB_PASSWORD: '$MYSQL_DB_PASSWORD'
            MYSQL_DB_NAME: '$MYSQL_DB_NAME'
            NEW_RELIC_LICENSE_KEY: '$NEW_RELIC_LICENSE_KEY'
            NEW_RELIC_APP_NAME: '$NEW_RELIC_APP_NAME'
            NEW_RELIC_LOG_LEVEL: '$NEW_RELIC_LOG_LEVEL'
          " | microk8s kubectl apply --namespace lidm-app-milestone -f -

  deploy:
    needs: configure
    runs-on: self-hosted

    steps:
      - name: Deploy to Kubernetes
        run: |
          microk8s kubectl apply -f microservices/app-milestone-backend/k8s --namespace lidm-app-milestone